#!/usr/bin/env perl

use v5.14;
use utf8;
use strict;
use warnings;

use Perl6::Say;

unless (-e "elasticsearch/") {
    say "Download and install elasticsearch...";
    system "curl -O https://download.elastic.co/elasticsearch/elasticsearch/elasticsearch-1.6.0.tar.gz 2>/dev/null; tar zxf elasticsearch-1.6.0.tar.gz; mv elasticsearch-1.6.0 elasticsearch; rm -f elasticsearch-1.6.0.tar.gz";
    say "elasticsearch setup was done";
}

my $plugins = [qw{
    mobz/elasticsearch-head
    royrusso/elasticsearch-HQ
    polyfractal/elasticsearch-inquisitor
    elasticsearch/elasticsearch-analysis-kuromoji/2.6.0
    elasticsearch/elasticsearch-analysis-icu/2.6.0
}];
for my $plugin (@$plugins) {
    say "Install $plugin...";
    system "./elasticsearch/bin/plugin --silent install $plugin";
}
